//! `setup_config()` (`initdb.c:1283`): the four configuration files a new
//! cluster gets, as pure functions over the vendored `.sample` templates.
//!
//! Everything here is a calculation. The templates are compiled in with
//! `include_str!` (ADR-0002: there is no `share/` directory on the host to read
//! them from), the values `setup_config` would have probed for arrive as
//! [`Settings`], and each `render_*` returns the exact bytes upstream's
//! `writefile` would have written. Creating the files, and probing the machine
//! for the values, are separate and live elsewhere.
//!
//! The two string surgeons are upstream's, transcribed rather than reimagined:
//! [`replace_token`] (`initdb.c:473`) rewrites the first occurrence of a literal
//! on each line, and [`replace_guc_value`] (`initdb.c:528`) rewrites a
//! possibly-commented-out assignment, keeping the file's spelling of the
//! parameter name and re-aligning any trailing comment. Neither uses a regular
//! expression, exactly as upstream notes: "this does most of what sed was used
//! for in the shell script, but doesn't need any regexp stuff".

use crate::cli::Options;
use crate::file_perm::{DataDirPerm, PG_DIR_MODE_GROUP};
use crate::pg_config;

/// SHA-256, used only by the provenance gate in `tests` and therefore not
/// compiled into the binary. See that module's header for why this crate
/// carries its own instead of borrowing `rlibpq`'s.
#[cfg(test)]
mod sha256;

/// `src/backend/utils/misc/postgresql.conf.sample`, vendored byte for byte.
pub const POSTGRESQL_CONF_SAMPLE: &str = include_str!("../share/postgresql.conf.sample");

/// `src/backend/libpq/pg_hba.conf.sample`, vendored byte for byte.
pub const PG_HBA_CONF_SAMPLE: &str = include_str!("../share/pg_hba.conf.sample");

/// `src/backend/libpq/pg_ident.conf.sample`, vendored byte for byte.
pub const PG_IDENT_CONF_SAMPLE: &str = include_str!("../share/pg_ident.conf.sample");

/// `initdb.c:208` — `AUTHTRUST_WARNING`, the block `@authcomment@` becomes when
/// either side of the cluster is configured for `trust`.
pub const AUTHTRUST_WARNING: &str = concat!(
    "# CAUTION: Configuring the system for local \"trust\" authentication\n",
    "# allows any local user to connect as any PostgreSQL user, including\n",
    "# the database superuser.  If you do not trust all your local users,\n",
    "# use another authentication method.\n",
);

/// `initdb.c:1443` — the whole of `postgresql.auto.conf`, which is not built
/// from a template at all but from two literal lines.
pub const POSTGRESQL_AUTO_CONF: &str = concat!(
    "# Do not edit this file manually!\n",
    "# It will be overwritten by the ALTER SYSTEM command.\n",
);

/// The four files `setup_config` writes, in the order it writes them.
pub const CONF_FILES: [&str; 4] = [
    "postgresql.conf",
    "postgresql.auto.conf",
    "pg_hba.conf",
    "pg_ident.conf",
];

// --------------------------------------------------------------------------
// Data
// --------------------------------------------------------------------------

/// `initdb.c:1326` — the date order `locale_date_order()` (`:2143`) reports for
/// `lc_time`, and so which `DateStyle` the cluster gets.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum DateOrder {
    /// `DATEORDER_YMD` → `iso, ymd`.
    Ymd,
    /// `DATEORDER_DMY` → `iso, dmy`.
    Dmy,
    /// `DATEORDER_MDY` → `iso, mdy`. Upstream's `result = DATEORDER_MDY;
    /// /* default */` (`:2153`), which is also what every early return keeps.
    #[default]
    Mdy,
}

impl DateOrder {
    /// The `datestyle` value for this order (`initdb.c:1328`, `:1331`, `:1335`).
    #[must_use]
    pub fn datestyle(self) -> &'static str {
        match self {
            Self::Ymd => "iso, ymd",
            Self::Dmy => "iso, dmy",
            Self::Mdy => "iso, mdy",
        }
    }
}

/// The resolved `authmethodlocal` / `authmethodhost` pair (`initdb.c:157`).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct AuthMethods {
    /// `authmethodlocal`, substituted for `@authmethodlocal@`.
    pub local: String,
    /// `authmethodhost`, substituted for `@authmethodhost@`.
    pub host: String,
}

impl Default for AuthMethods {
    /// Both unspecified, so both `trust` (`check_authmethod_unspecified`,
    /// `initdb.c:2572`).
    fn default() -> Self {
        Self {
            local: String::from("trust"),
            host: String::from("trust"),
        }
    }
}

impl AuthMethods {
    /// `initdb.c:3246` (the `-A` arm) followed by `check_authmethod_unspecified`
    /// (`:3457`, `:3458`).
    ///
    /// `-A` sets both sides, with upstream's two mirrored special cases: `ident`
    /// is meaningless on a Unix socket so the local side becomes `peer`, and
    /// `peer` is meaningless over TCP/IP so the host side becomes `ident`.
    /// `--auth-local` and `--auth-host` then override their own side.
    ///
    /// Divergence (`docs/divergences.md`): C's getopt applies the three
    /// switches in command-line order, so a `-A` written *after* `--auth-host`
    /// wins there and loses here. usage-rs reports which switches were given,
    /// not where.
    #[must_use]
    pub fn resolve(options: &Options) -> Self {
        let mut methods = Self::default();
        if let Some(both) = options.auth.as_deref() {
            both.clone_into(&mut methods.local);
            both.clone_into(&mut methods.host);
            if methods.host == "ident" {
                methods.local = String::from("peer");
            } else if methods.local == "peer" {
                methods.host = String::from("ident");
            }
        }
        if let Some(local) = options.auth_local.as_deref() {
            local.clone_into(&mut methods.local);
        }
        if let Some(host) = options.auth_host.as_deref() {
            host.clone_into(&mut methods.host);
        }
        methods
    }

    /// `initdb.c:1518` — `@authcomment@` is the warning when either side trusts.
    #[must_use]
    pub fn auth_comment(&self) -> &'static str {
        if self.local == "trust" || self.host == "trust" {
            AUTHTRUST_WARNING
        } else {
            ""
        }
    }

    /// `initdb.c:1406` — md5 on one side, and not scram-sha-256 on the other,
    /// drags `password_encryption` back to md5.
    #[must_use]
    pub fn forces_md5_password_encryption(&self) -> bool {
        (self.local == "md5" && self.host != "scram-sha-256")
            || (self.host == "md5" && self.local != "scram-sha-256")
    }
}

/// Everything `setup_config` has already decided by the time it opens the
/// template: the probe results, the locale, the auth methods and the `-c`
/// overrides.
///
/// Probing the machine for `max_connections`, `shared_buffers`, the time zone
/// and the DSM implementation (`test_config_settings`, `initdb.c:1140`) is an
/// action of its own; this struct is where its answers arrive.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Settings {
    /// `n_connections` (`initdb.c:1185`).
    pub max_connections: u32,
    /// `n_av_slots`, which upstream derives as `AV_SLOTS_FOR_CONNS(nconns)`
    /// = `nconns / 6` (`initdb.c:1135`).
    pub autovacuum_worker_slots: u32,
    /// `n_buffers`, in blocks of [`pg_config::BLCKSZ`] (`initdb.c:1204`).
    pub shared_buffers_blocks: u32,
    /// `lc_messages`, `lc_monetary`, `lc_numeric`, `lc_time`, in that order.
    pub lc_messages: String,
    /// See [`Settings::lc_messages`].
    pub lc_monetary: String,
    /// See [`Settings::lc_messages`].
    pub lc_numeric: String,
    /// See [`Settings::lc_messages`].
    pub lc_time: String,
    /// `locale_date_order(lc_time)` (`initdb.c:1326`).
    pub date_order: DateOrder,
    /// `default_text_search_config`, *without* the `pg_catalog.` prefix
    /// `setup_config` adds (`initdb.c:1343`).
    pub default_text_search_config: String,
    /// `default_timezone`; `None` when `select_default_timezone` found none, in
    /// which case upstream leaves both timezone lines commented (`:1348`).
    pub default_timezone: Option<String>,
    /// `dynamic_shared_memory_type` (`choose_dsm_implementation`, `:1157`).
    pub dynamic_shared_memory_type: String,
    /// `wal_segment_size_mb` (`initdb.c:169`, `--wal-segsize`).
    pub wal_segment_size_mb: u32,
    /// The resolved `-A` / `--auth-local` / `--auth-host` pair.
    pub auth: AuthMethods,
    /// `pg_dir_create_mode` and friends; only `PG_DIR_MODE_GROUP` is consulted
    /// here, for `log_file_mode` (`initdb.c:1421`).
    pub perm: DataDirPerm,
    /// `-c NAME=VALUE`, in command-line order (`extra_guc_names`/`_values`).
    pub gucs: Vec<(String, String)>,
    /// Whether `getaddrinfo("::1", …)` succeeded (`initdb.c:1470`). When it did
    /// not, the two `::1` lines of `pg_hba.conf` are commented out.
    pub ipv6_supported: bool,
}

impl Default for Settings {
    /// The values a stock build lands on with `--no-locale` and no probing:
    /// enough for a unit test to say what it is actually varying.
    fn default() -> Self {
        Self {
            max_connections: 100,
            autovacuum_worker_slots: 16,
            shared_buffers_blocks: 16384,
            lc_messages: String::from("C"),
            lc_monetary: String::from("C"),
            lc_numeric: String::from("C"),
            lc_time: String::from("C"),
            date_order: DateOrder::Mdy,
            default_text_search_config: String::from("simple"),
            default_timezone: Some(String::from("GMT")),
            dynamic_shared_memory_type: String::from("posix"),
            wal_segment_size_mb: pg_config::DEFAULT_WAL_SEGMENT_SIZE_MB,
            auth: AuthMethods::default(),
            perm: DataDirPerm::OWNER,
            gucs: Vec::new(),
            ipv6_supported: true,
        }
    }
}

// --------------------------------------------------------------------------
// Calculations: upstream's string surgery
// --------------------------------------------------------------------------

/// C's `isspace()` in the "C" locale, which includes the vertical tab Rust's
/// [`u8::is_ascii_whitespace`] leaves out.
fn is_c_space(byte: u8) -> bool {
    matches!(byte, b' ' | b'\t' | b'\n' | 0x0b | 0x0c | b'\r')
}

/// `pg_strncasecmp(a, b, n) == 0`, over the first `n` bytes.
fn starts_with_ignoring_ascii_case(haystack: &[u8], needle: &[u8]) -> bool {
    haystack.len() >= needle.len() && haystack[..needle.len()].eq_ignore_ascii_case(needle)
}

/// `readfile()` (`initdb.c:676`): the file as lines, each keeping its own
/// newline, and a final line without one kept as it is.
///
/// Upstream reads with `pg_get_line_buf`, which keeps the terminator; the
/// round trip through [`join_lines`] is therefore the identity.
#[must_use]
pub fn split_lines(text: &str) -> Vec<String> {
    let mut lines = Vec::new();
    let mut rest = text;
    while !rest.is_empty() {
        if let Some(end) = rest.find('\n') {
            lines.push(rest[..=end].to_owned());
            rest = &rest[end + 1..];
        } else {
            lines.push(rest.to_owned());
            break;
        }
    }
    lines
}

/// `writefile()` (`initdb.c:723`): the lines `fputs`'d back out, nothing added.
#[must_use]
pub fn join_lines(lines: &[String]) -> String {
    lines.concat()
}

/// `replace_token()` (`initdb.c:473`): replace `token` with `replacement` the
/// **first** time it occurs on each line.
#[must_use]
pub fn replace_token(lines: Vec<String>, token: &str, replacement: &str) -> Vec<String> {
    lines
        .into_iter()
        .map(|line| match line.find(token) {
            None => line,
            Some(at) => {
                let mut new = String::with_capacity(line.len() + replacement.len());
                new.push_str(&line[..at]);
                new.push_str(replacement);
                new.push_str(&line[at + token.len()..]);
                new
            }
        })
        .collect()
}

/// `guc_value_requires_quotes()` (`initdb.c:644`): identifiers and numbers with
/// optional unit letters go in bare; everything else is quoted.
#[must_use]
pub fn guc_value_requires_quotes(value: &str) -> bool {
    let bytes = value.as_bytes();
    let Some(&first) = bytes.first() else {
        return true; // empty string must be quoted
    };
    if first.is_ascii_alphabetic() {
        // an identifier: letters and digits all the way down
        return !bytes.iter().all(u8::is_ascii_alphanumeric);
    }
    if first.is_ascii_digit() {
        // a number, then zero or more unit letters
        let after_digits = bytes
            .iter()
            .position(|b| !b.is_ascii_digit())
            .unwrap_or(bytes.len());
        return !bytes[after_digits..].iter().all(u8::is_ascii_alphabetic);
    }
    true // all else must be quoted
}

/// `escape_quotes()` (`initdb.c:406`) via `escape_single_quotes_ascii()`
/// (`src/port/quotes.c:34`): double every single quote and every backslash.
#[must_use]
pub fn escape_quotes(src: &str) -> String {
    let mut out = String::with_capacity(src.len());
    for ch in src.chars() {
        if ch == '\'' || ch == '\\' {
            out.push(ch);
        }
        out.push(ch);
    }
    out
}

/// The prepared replacement line, before the comment and the newline:
/// `[#]name = value`, with the value quoted if it has to be.
fn prepared_assignment(guc_name: &str, guc_value: &str, mark_as_comment: bool) -> String {
    let mut line = String::new();
    if mark_as_comment {
        line.push('#');
    }
    line.push_str(guc_name);
    line.push_str(" = ");
    if guc_value_requires_quotes(guc_value) {
        line.push('\'');
        line.push_str(&escape_quotes(guc_value));
        line.push('\'');
    } else {
        line.push_str(guc_value);
    }
    line
}

/// A line of the template that assigns `guc_name`, located the way
/// `replace_guc_value` locates one (`initdb.c:547`-`:563`): skip any mix of
/// `#` and whitespace, match the name case-insensitively, skip whitespace
/// again, and require an `=`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
struct Assignment {
    /// Byte offset of the name as the *file* spells it, for the canonical
    /// casing `initdb.c:566` copies over the prepared line.
    name_start: usize,
    /// Byte offset of the `=`, where upstream's `strrchr(where, '#')` for the
    /// trailing comment starts.
    equals_at: usize,
}

fn find_assignment(line: &str, guc_name: &str) -> Option<Assignment> {
    let bytes = line.as_bytes();
    let mut at = 0;
    while at < bytes.len() && (bytes[at] == b'#' || is_c_space(bytes[at])) {
        at += 1;
    }
    if !starts_with_ignoring_ascii_case(&bytes[at..], guc_name.as_bytes()) {
        return None;
    }
    let name_start = at;
    at += guc_name.len();
    while at < bytes.len() && is_c_space(bytes[at]) {
        at += 1;
    }
    if bytes.get(at) != Some(&b'=') {
        return None;
    }
    Some(Assignment {
        name_start,
        equals_at: at,
    })
}

/// De-tabified column of byte offset `upto`, tab stops every 8 columns
/// (`initdb.c:618`).
fn detabified_column(line: &str, upto: usize) -> usize {
    let mut column = 0;
    for &byte in &line.as_bytes()[..upto] {
        if byte == b'\t' {
            column += 8 - (column % 8);
        } else {
            column += 1;
        }
    }
    column
}

/// `replace_guc_value()` (`initdb.c:528`): replace the possibly-commented-out
/// assignment of `guc_name` with a live assignment of `guc_value`, appending a
/// new line when the file has no such assignment at all.
///
/// The match is case-insensitive and the **file's** spelling of the name is
/// what gets written (`initdb.c:566`), so `-c WORK_MEM=512` produces
/// `work_mem = 512`. Only the first match is replaced ("we assume there's at
/// most one matching assignment"), and any trailing comment is carried over at
/// its original de-tabified column.
#[must_use]
pub fn replace_guc_value(
    mut lines: Vec<String>,
    guc_name: &str,
    guc_value: &str,
    mark_as_comment: bool,
) -> Vec<String> {
    let prepared = prepared_assignment(guc_name, guc_value, mark_as_comment);

    for line in &mut lines {
        let Some(found) = find_assignment(line, guc_name) else {
            continue;
        };

        // "found it -- let's use the canonical casing shown in the file": the
        // name sits at offset 0, or 1 past the '#', of the prepared line.
        let name_start = usize::from(mark_as_comment);
        let file_spelling = &line[found.name_start..found.name_start + guc_name.len()];
        let mut new = prepared.clone();
        new.replace_range(name_start..name_start + guc_name.len(), file_spelling);

        match line[found.equals_at..]
            .rfind('#')
            .map(|at| found.equals_at + at)
        {
            Some(comment_at) => {
                // Preserve the comment's column, forcing at least one space.
                let old_indent = detabified_column(line, comment_at);
                let mut new_indent = new.len();
                let target = old_indent.max(new_indent + 1);
                while new_indent < target {
                    let if_tab = new_indent + 8 - (new_indent % 8);
                    if if_tab <= target {
                        new.push('\t');
                        new_indent = if_tab;
                    } else {
                        new.push(' ');
                        new_indent += 1;
                    }
                }
                // The old comment carries the original newline with it.
                new.push_str(&line[comment_at..]);
            }
            None => new.push('\n'),
        }

        *line = new;
        return lines; // "assume there's only one match"
    }

    // No match, so append a new entry.
    lines.push(prepared + "\n");
    lines
}

// --------------------------------------------------------------------------
// Calculations: the values setup_config formats
// --------------------------------------------------------------------------

/// `pretty_wal_size()` (`initdb.c:1266`): `segment_count` segments as `GB` when
/// that is a whole number of gigabytes, otherwise `MB`.
#[must_use]
pub fn pretty_wal_size(segment_count: u32, wal_segment_size_mb: u32) -> String {
    let size = wal_segment_size_mb * segment_count;
    if size.is_multiple_of(1024) {
        format!("{}GB", size / 1024)
    } else {
        format!("{size}MB")
    }
}

/// `initdb.c:1310`: `n_buffers` blocks as `MB` when that is a whole number of
/// megabytes, otherwise `kB`.
#[must_use]
pub fn shared_buffers_value(n_buffers: u32) -> String {
    let kilobytes = n_buffers * (pg_config::BLCKSZ / 1024);
    if kilobytes.is_multiple_of(1024) {
        format!("{}MB", kilobytes / 1024)
    } else {
        format!("{kilobytes}kB")
    }
}

/// `initdb.c:1377`: a flush-after default, measured in blocks, rendered in kB.
#[must_use]
pub fn flush_after_value(blocks: u32) -> String {
    format!("{}kB", blocks * (pg_config::BLCKSZ / 1024))
}

// --------------------------------------------------------------------------
// Calculations: the four files
// --------------------------------------------------------------------------

/// `setup_config`'s `postgresql.conf` half (`initdb.c:1289`-`:1439`), in
/// upstream's order — which matters, because a `-c` override re-aligns the
/// comment on a line an earlier replacement has already rewritten.
#[must_use]
pub fn render_postgresql_conf(sample: &str, settings: &Settings) -> String {
    let mut lines = split_lines(sample);

    let set = |lines, name: &str, value: &str| replace_guc_value(lines, name, value, false);
    let comment = |lines, name: &str, value: &str| replace_guc_value(lines, name, value, true);

    lines = set(
        lines,
        "max_connections",
        &settings.max_connections.to_string(),
    );
    lines = set(
        lines,
        "autovacuum_worker_slots",
        &settings.autovacuum_worker_slots.to_string(),
    );
    lines = set(
        lines,
        "shared_buffers",
        &shared_buffers_value(settings.shared_buffers_blocks),
    );
    lines = set(lines, "lc_messages", &settings.lc_messages);
    lines = set(lines, "lc_monetary", &settings.lc_monetary);
    lines = set(lines, "lc_numeric", &settings.lc_numeric);
    lines = set(lines, "lc_time", &settings.lc_time);
    lines = set(lines, "datestyle", settings.date_order.datestyle());
    lines = set(
        lines,
        "default_text_search_config",
        &format!("pg_catalog.{}", settings.default_text_search_config),
    );
    if let Some(timezone) = settings.default_timezone.as_deref() {
        lines = set(lines, "timezone", timezone);
        lines = set(lines, "log_timezone", timezone);
    }
    lines = set(
        lines,
        "dynamic_shared_memory_type",
        &settings.dynamic_shared_memory_type,
    );

    // "Caution: these depend on wal_segment_size_mb, they're not constants"
    lines = set(
        lines,
        "min_wal_size",
        &pretty_wal_size(
            pg_config::DEFAULT_MIN_WAL_SEGS,
            settings.wal_segment_size_mb,
        ),
    );
    lines = set(
        lines,
        "max_wal_size",
        &pretty_wal_size(
            pg_config::DEFAULT_MAX_WAL_SEGS,
            settings.wal_segment_size_mb,
        ),
    );

    // Entries fixed up to the true compile-time defaults stay commented.
    lines = comment(
        lines,
        "unix_socket_directories",
        pg_config::DEFAULT_PGSOCKET_DIR,
    );
    lines = comment(lines, "port", pg_config::DEF_PGPORT_STR);
    for (name, blocks) in pg_config::FLUSH_AFTER_DEFAULTS {
        if blocks > 0 {
            lines = comment(lines, name, &flush_after_value(blocks));
        }
    }
    if pg_config::UPDATE_PROCESS_TITLE_OFF {
        lines = comment(lines, "update_process_title", "off");
    }

    if settings.auth.forces_md5_password_encryption() {
        lines = set(lines, "password_encryption", "md5");
    }
    if settings.perm.dir_mode == PG_DIR_MODE_GROUP {
        lines = set(lines, "log_file_mode", "0640");
    }

    // "Now replace anything that's overridden via -c switches."
    for (name, value) in &settings.gucs {
        lines = set(lines, name, value);
    }

    join_lines(&lines)
}

/// `initdb.c:1443` — `postgresql.auto.conf` is two literal lines.
#[must_use]
pub fn render_postgresql_auto_conf() -> String {
    POSTGRESQL_AUTO_CONF.to_owned()
}

/// `setup_config`'s `pg_hba.conf` half (`initdb.c:1460`-`:1519`).
#[must_use]
pub fn render_pg_hba_conf(sample: &str, settings: &Settings) -> String {
    let mut lines = split_lines(sample);

    lines = replace_token(lines, "@remove-line-for-nolocal@", "");

    // Without platform support for IPv6, comment out the two `::1` records.
    if !settings.ipv6_supported {
        lines = replace_token(
            lines,
            "host    all             all             ::1",
            "#host    all             all             ::1",
        );
        lines = replace_token(
            lines,
            "host    replication     all             ::1",
            "#host    replication     all             ::1",
        );
    }

    lines = replace_token(lines, "@authmethodhost@", &settings.auth.host);
    lines = replace_token(lines, "@authmethodlocal@", &settings.auth.local);
    lines = replace_token(lines, "@authcomment@", settings.auth.auth_comment());

    join_lines(&lines)
}

/// `setup_config`'s `pg_ident.conf` half (`initdb.c:1527`): the template,
/// copied through unchanged.
///
/// Upstream still goes `readfile` → `writefile`, but it replaces no token on
/// the way, and that round trip is the identity (`split_lines` keeps every
/// terminator) — so this is the same bytes without the intermediate `Vec`.
#[must_use]
pub fn render_pg_ident_conf(sample: &str) -> String {
    sample.to_owned()
}

/// The four files, in `setup_config` order, as `(name, contents)`.
///
/// Every one of them is then `chmod`ed to `pg_file_create_mode`
/// (`initdb.c:1441`, `:1457`, `:1523`, `:1532`); the mode is
/// [`Settings::perm`]'s `file_mode` and belongs to whoever writes them.
#[must_use]
pub fn render_all(settings: &Settings) -> Vec<(&'static str, String)> {
    vec![
        (
            CONF_FILES[0],
            render_postgresql_conf(POSTGRESQL_CONF_SAMPLE, settings),
        ),
        (CONF_FILES[1], render_postgresql_auto_conf()),
        (
            CONF_FILES[2],
            render_pg_hba_conf(PG_HBA_CONF_SAMPLE, settings),
        ),
        (CONF_FILES[3], render_pg_ident_conf(PG_IDENT_CONF_SAMPLE)),
    ]
}

#[cfg(test)]
mod tests {
    use super::*;

    /// None of the four `@…@` placeholders may reach a written file. A bare
    /// `@` may: the template's own prose explains the `@file` include syntax.
    fn assert_no_tokens_survive(rendered: &str) {
        for token in [
            "@remove-line-for-nolocal@",
            "@authmethodlocal@",
            "@authmethodhost@",
            "@authcomment@",
        ] {
            assert!(!rendered.contains(token), "{token} survived");
        }
    }

    /// The value assigned to `name` in a rendered file, comment and all.
    fn line_for<'a>(rendered: &'a str, name: &str) -> Option<&'a str> {
        rendered
            .lines()
            .find(|line| line.starts_with(&format!("{name} = ")))
    }

    // --- readfile / writefile ------------------------------------------

    /// FNV-1a (64-bit), so the digests below need no dependency and no
    /// `unsafe`. It is not a cryptographic hash and is not being used as one:
    /// it guards against an accidental edit, not against a forged one.
    fn fnv1a64(bytes: &[u8]) -> u64 {
        let mut hash: u64 = 0xcbf2_9ce4_8422_2325;
        for byte in bytes {
            hash ^= u64::from(*byte);
            hash = hash.wrapping_mul(0x0000_0100_0000_01b3);
        }
        hash
    }

    /// Pins the divergence in `docs/divergences.md`: these three files are
    /// compiled in, so a cluster gets *these* bytes and never the ones in a
    /// host's `share/`. What upstream ships is therefore part of this crate's
    /// observable behaviour, and drifting from it has to be a deliberate act.
    ///
    /// A failure here means a template changed. That is legitimate when
    /// PostgreSQL 18.x changes one — re-vendor from upstream (tag `REL_18_6`
    /// or the published tarball, never pgrust's tree; see ADR-0007), update
    /// the digest, and say so on the Linear issue — and is a bug in every
    /// other case, including a stray editor reformat or a line-ending
    /// conversion. The lengths are asserted too so the failure says *which*
    /// file and by how much.
    ///
    /// A digest proves only "unchanged since someone pinned it", never
    /// "upstream's". It is computed *from* the file, so whatever bytes were
    /// vendored are the bytes it blesses — which is how a pgrust-modified
    /// `postgresql.conf.sample` shipped here and passed. The tests below
    /// assert against expectations written down from upstream instead —
    /// upstream's own SHA-256 of each file, its section banners, and the
    /// absence of any namespaced setting.
    #[test]
    fn the_embedded_templates_are_the_postgresql_18_6_bytes_we_vendored() {
        for (name, sample, length, digest) in [
            (
                "postgresql.conf.sample",
                POSTGRESQL_CONF_SAMPLE,
                32_652,
                0x364a_ac11_a839_c67f_u64,
            ),
            (
                "pg_hba.conf.sample",
                PG_HBA_CONF_SAMPLE,
                5_635,
                0x0a0d_1bd3_d9f1_4f98,
            ),
            (
                "pg_ident.conf.sample",
                PG_IDENT_CONF_SAMPLE,
                2_681,
                0xda9b_59c0_b8dd_0769,
            ),
        ] {
            assert_eq!(sample.len(), length, "{name} changed length");
            assert_eq!(fnv1a64(sample.as_bytes()), digest, "{name} changed content");
        }
    }

    // --- provenance: is this pristine PostgreSQL 18.6? ------------------

    /// The release the templates are copies of, in the two forms PostgreSQL
    /// publishes it. These are facts about *upstream*, recorded here (and in
    /// `crates/rinitdb/share/README.md`) from PostgreSQL's own artifacts, so
    /// nothing below is derived from the vendored bytes it judges.
    const UPSTREAM_TAG: &str = "REL_18_6";
    const UPSTREAM_COMMIT: &str = "724edf9bde9d356724ad384a2e196edc3c9f80f7";
    const UPSTREAM_TARBALL: &str =
        "https://ftp.postgresql.org/pub/source/v18.6/postgresql-18.6.tar.bz2";
    /// The tarball's own digest, as published at `…/postgresql-18.6.tar.bz2.sha256`.
    const UPSTREAM_TARBALL_SHA256: &str =
        "555610c24d53e4316da5b7d3fc25c279d96856d5e0e23ee308c328c5fa881d9f";

    /// Each template as `(vendored name, embedded bytes, upstream path,
    /// upstream SHA-256)`. The digests are the ones `sha256sum` prints for
    /// these files in the tarball above and at tag [`UPSTREAM_TAG`]; the two
    /// sources were checked against each other and agree.
    const UPSTREAM_SAMPLES: [(&str, &str, &str, &str); 3] = [
        (
            "postgresql.conf.sample",
            POSTGRESQL_CONF_SAMPLE,
            "src/backend/utils/misc/postgresql.conf.sample",
            "93e3da1fc8d667ba086ee239e5f053581739648a90566f191666cc63de16357f",
        ),
        (
            "pg_hba.conf.sample",
            PG_HBA_CONF_SAMPLE,
            "src/backend/libpq/pg_hba.conf.sample",
            "e3abfe29646ac6ece67e92d0b5255eb3b35d2878d23c7ea6bbd94f100054c168",
        ),
        (
            "pg_ident.conf.sample",
            PG_IDENT_CONF_SAMPLE,
            "src/backend/libpq/pg_ident.conf.sample",
            "bf8f1664dc42eeb78a71a3746afb6b6c93805bda55ff4504f796dbe339d1fa50",
        ),
    ];

    /// What a reader of the failure has to be told: which file drifted, by how
    /// much, what the file is supposed to be, where to get that, and which
    /// tree is never the answer.
    fn drift_report(name: &str, upstream_path: &str, upstream: &str, vendored: &str) -> String {
        [
            format!("{name} is not the file PostgreSQL 18.6 ships."),
            String::new(),
            format!("    upstream sha256: {upstream}"),
            format!("    vendored sha256: {vendored}"),
            String::new(),
            String::from(
                "The upstream digest was recorded from PostgreSQL's own release, not \
                 computed from this file, so a mismatch says the vendored copy is not \
                 pristine upstream. It does not say a pin has gone stale.",
            ),
            String::new(),
            format!(
                "Re-fetch {upstream_path} from {UPSTREAM_TARBALL} (published sha256 \
                 {UPSTREAM_TARBALL_SHA256}), or from postgres/postgres at tag \
                 {UPSTREAM_TAG}, commit {UPSTREAM_COMMIT}."
            ),
            String::new(),
            String::from(
                "Never re-vendor from pgrust's crates/postgres-18.6-reference/ tree. It \
                 is a modified checkout: its postgresql.conf.sample carries a 41-line \
                 `# PGRUST` section of pgrust-only GUCs, and copying pgrust's own work \
                 into this MIT crate breaks ADR-0003. That tree is where the earlier \
                 contamination came from, and is why this test exists.",
            ),
            String::new(),
            String::from(
                "Moving to a newer PostgreSQL is a deliberate act: update UPSTREAM_SAMPLES \
                 here and crates/rinitdb/share/README.md in the same commit, and say so in \
                 progress.md.",
            ),
        ]
        .join("\n")
    }

    /// Pins the templates to upstream's *identity*, not to their own past.
    ///
    /// The digest test above can only ever prove "unchanged since someone
    /// vendored this"; it faithfully blessed the pgrust-contaminated sample
    /// and passed. A SHA-256 recorded from PostgreSQL's release artifacts is a
    /// claim about what the file must be, checkable by anyone with
    /// `sha256sum` and the tarball, and it fails the moment a vendored file is
    /// anything other than what 18.6 shipped.
    #[test]
    fn each_embedded_template_is_the_file_postgresql_18_6_ships() {
        for (name, sample, upstream_path, upstream) in UPSTREAM_SAMPLES {
            let vendored = sha256::digest_hex(sample.as_bytes());
            assert_eq!(
                vendored,
                upstream,
                "{}",
                drift_report(name, upstream_path, upstream, &vendored)
            );
        }
    }

    #[test]
    fn the_drift_report_says_what_broke_and_where_to_get_the_real_file() {
        let report = drift_report(
            "postgresql.conf.sample",
            "src/backend/utils/misc/postgresql.conf.sample",
            "expected-digest",
            "actual-digest",
        );

        for expected in [
            "postgresql.conf.sample",
            "expected-digest",
            "actual-digest",
            UPSTREAM_TARBALL,
            UPSTREAM_TAG,
            UPSTREAM_COMMIT,
            "crates/postgres-18.6-reference/",
            "crates/rinitdb/share/README.md",
        ] {
            assert!(
                report.contains(expected),
                "the report never mentions {expected}"
            );
        }
    }

    /// The banner titles of PostgreSQL 18.6's `postgresql.conf.sample`, in
    /// upstream order (`src/backend/utils/misc/postgresql.conf.sample`,
    /// tag `REL_18_6`). Written out here from upstream rather than read back
    /// out of the vendored file, so it is a statement about what the file may
    /// contain and not a restatement of what it does contain.
    const UPSTREAM_CONF_SECTIONS: [&str; 15] = [
        "FILE LOCATIONS",
        "CONNECTIONS AND AUTHENTICATION",
        "RESOURCE USAGE (except WAL)",
        "WRITE-AHEAD LOG",
        "REPLICATION",
        "QUERY TUNING",
        "REPORTING AND LOGGING",
        "STATISTICS",
        "VACUUMING",
        "CLIENT CONNECTION DEFAULTS",
        "LOCK MANAGEMENT",
        "VERSION AND PLATFORM COMPATIBILITY",
        "ERROR HANDLING",
        "CONFIG FILE INCLUDES",
        "CUSTOMIZED OPTIONS",
    ];

    /// A `#-----…` rule: a `#` followed only by dashes.
    fn is_banner_rule(line: &str) -> bool {
        line.len() > 2 && line.starts_with('#') && line[1..].bytes().all(|byte| byte == b'-')
    }

    /// The title of every rule-title-rule banner in a `postgresql.conf`
    /// template, in file order.
    fn section_titles(sample: &str) -> Vec<&str> {
        let lines: Vec<&str> = sample.lines().collect();
        lines
            .windows(3)
            .filter(|window| is_banner_rule(window[0]) && is_banner_rule(window[2]))
            .filter_map(|window| window[1].strip_prefix("# "))
            .collect()
    }

    /// The name assigned on a line, whether or not the line is commented out:
    /// `#work_mem = 4MB` and `work_mem = 4MB` both yield `work_mem`.
    fn assigned_name(line: &str) -> Option<&str> {
        let (name, _) = line.trim_start().trim_start_matches('#').split_once('=')?;
        let name = name.trim();
        let is_identifier = !name.is_empty()
            && name
                .bytes()
                .all(|byte| byte.is_ascii_alphanumeric() || byte == b'_' || byte == b'.');
        is_identifier.then_some(name)
    }

    /// Catches a vendor-specific block appended to the sample — exactly the
    /// 41-line `# PGRUST` section that pgrust's `postgres-18.6-reference`
    /// tree carries and that was vendored here by mistake. A settings block
    /// has to announce itself with a banner to be readable, so pinning the
    /// banner list against upstream's catches the block as a whole, including
    /// one renamed to something less obvious than `PGRUST`.
    #[test]
    fn the_conf_sample_carries_only_upstreams_sections() {
        assert_eq!(
            section_titles(POSTGRESQL_CONF_SAMPLE),
            UPSTREAM_CONF_SECTIONS,
            "a section upstream does not ship: the sample is not pristine \
             PostgreSQL 18.6 (see crates/rinitdb/share/README.md)"
        );
    }

    /// Catches a vendor GUC smuggled *inside* an upstream section, where no
    /// new banner would give it away — `pgrust.admission_bypass` and friends.
    /// Upstream's sample documents only core GUCs, and a core GUC never has a
    /// prefix: a dot means an extension's namespace, which upstream leaves to
    /// the empty `CUSTOMIZED OPTIONS` section for the operator to fill in.
    #[test]
    fn no_setting_in_the_conf_sample_is_namespaced_like_an_extension() {
        let namespaced: Vec<&str> = POSTGRESQL_CONF_SAMPLE
            .lines()
            .filter_map(assigned_name)
            .filter(|name| name.contains('.'))
            .collect();
        assert!(
            namespaced.is_empty(),
            "non-upstream namespaced settings in the sample: {namespaced:?}"
        );
    }

    /// The tokens `setup_config` substitutes have to still be in the template
    /// it is handed, or a replacement would quietly become a no-op and the
    /// digest above would be the only thing standing between a cluster and a
    /// `pg_hba.conf` full of `@authmethodlocal@`.
    #[test]
    fn every_token_setup_config_replaces_is_present_in_the_template() {
        for token in [
            "@remove-line-for-nolocal@",
            "@authmethodlocal@",
            "@authmethodhost@",
            "@authcomment@",
        ] {
            assert!(PG_HBA_CONF_SAMPLE.contains(token), "{token} is gone");
        }
    }

    #[test]
    fn splitting_and_joining_is_the_identity_on_every_template() {
        for sample in [
            POSTGRESQL_CONF_SAMPLE,
            PG_HBA_CONF_SAMPLE,
            PG_IDENT_CONF_SAMPLE,
        ] {
            assert_eq!(join_lines(&split_lines(sample)), sample);
        }
    }

    #[test]
    fn a_line_keeps_its_own_newline_and_a_last_line_may_have_none() {
        assert_eq!(split_lines("a\nb\n"), ["a\n", "b\n"]);
        assert_eq!(split_lines("a\nb"), ["a\n", "b"]);
        assert_eq!(split_lines(""), Vec::<String>::new());
        assert_eq!(split_lines("\n"), ["\n"]);
    }

    // --- replace_token --------------------------------------------------

    #[test]
    fn a_token_is_replaced_once_per_line_not_once_per_file() {
        let lines = vec![String::from("x @t@ y @t@\n"), String::from("@t@\n")];
        assert_eq!(
            replace_token(lines, "@t@", "V"),
            ["x V y @t@\n", "V\n"],
            "upstream replaces the first occurrence on each line"
        );
    }

    #[test]
    fn an_absent_token_leaves_every_line_alone() {
        let lines = vec![String::from("nothing here\n")];
        assert_eq!(replace_token(lines.clone(), "@t@", "V"), lines);
    }

    #[test]
    fn the_nolocal_token_is_erased_rather_than_commented() {
        let rendered = render_pg_hba_conf(PG_HBA_CONF_SAMPLE, &Settings::default());
        assert!(!rendered.contains("@remove-line-for-nolocal@"));
        assert!(rendered.contains("# \"local\" is for Unix domain socket connections only\n"));
    }

    // --- guc_value_requires_quotes --------------------------------------

    #[test]
    fn an_identifier_and_a_number_with_units_go_in_bare() {
        for bare in ["posix", "off", "md5", "100", "128MB", "80MB", "1GB", "0640"] {
            assert!(!guc_value_requires_quotes(bare), "{bare}");
        }
    }

    #[test]
    fn everything_else_is_quoted() {
        for quoted in [
            "",
            "iso, mdy",
            "pg_catalog.simple",
            "scram-sha-256",
            "/tmp",
            "en_US.UTF-8",
            "128 MB",
            "12MB3",
            "-1",
            "2.0",
        ] {
            assert!(guc_value_requires_quotes(quoted), "{quoted}");
        }
    }

    #[test]
    fn a_quote_or_a_backslash_in_a_value_is_doubled() {
        assert_eq!(escape_quotes("it's"), "it''s");
        assert_eq!(escape_quotes(r"a\b"), r"a\\b");
        assert_eq!(escape_quotes("plain"), "plain");
        let lines = replace_guc_value(vec![String::from("#a = 1\n")], "a", "it's\\", false);
        assert_eq!(lines, ["a = 'it''s\\\\'\n"]);
    }

    // --- replace_guc_value: commented vs uncommented keys ---------------

    #[test]
    fn a_commented_key_is_uncommented_and_its_comment_column_is_kept() {
        let lines = vec![String::from(
            "#port = 5432\t\t\t\t# (change requires restart)\n",
        )];
        let out = replace_guc_value(lines, "port", "5432", true);
        assert_eq!(out, ["#port = 5432\t\t\t\t# (change requires restart)\n"]);

        let lines = vec![String::from(
            "#port = 5432\t\t\t\t# (change requires restart)\n",
        )];
        let out = replace_guc_value(lines, "port", "5432", false);
        // The comment stays at de-tabified column 40 either way; dropping the
        // '#' shortens the line by one byte, which a tab absorbs.
        assert_eq!(out, ["port = 5432\t\t\t\t# (change requires restart)\n"]);
    }

    #[test]
    fn an_already_uncommented_key_is_replaced_in_place() {
        let lines = vec![String::from("work_mem = 128\t\t\t\t# min 64kB\n")];
        let out = replace_guc_value(lines, "work_mem", "512", false);
        assert_eq!(out, ["work_mem = 512\t\t\t\t# min 64kB\n"]);
    }

    #[test]
    fn a_line_without_a_comment_gets_a_bare_newline() {
        let lines = vec![String::from("#timezone = 'GMT'\n")];
        let out = replace_guc_value(lines, "timezone", "Etc/UTC", false);
        assert_eq!(out, ["timezone = 'Etc/UTC'\n"]);
    }

    #[test]
    fn leading_whitespace_before_the_hash_is_tolerated() {
        let lines = vec![String::from("  \t#  work_mem = 4MB\n")];
        let out = replace_guc_value(lines, "work_mem", "8MB", false);
        assert_eq!(out, ["work_mem = 8MB\n"]);
    }

    #[test]
    fn a_name_that_is_only_a_prefix_of_the_key_does_not_match() {
        // `#work_mem = 4MB` must not be found when looking for `work`.
        let lines = vec![String::from("#work_mem = 4MB\t\t\t\t# min 64kB\n")];
        let out = replace_guc_value(lines, "work", "1", false);
        assert_eq!(
            out,
            ["#work_mem = 4MB\t\t\t\t# min 64kB\n", "work = 1\n"],
            "no match, so a new entry is appended"
        );
    }

    #[test]
    fn a_missing_key_is_appended_as_a_new_line() {
        let lines = vec![String::from("#a = 1\n")];
        let out = replace_guc_value(lines, "zzz", "yes", false);
        assert_eq!(out, ["#a = 1\n", "zzz = yes\n"]);
    }

    #[test]
    fn only_the_first_matching_assignment_is_replaced() {
        let lines = vec![String::from("#a = 1\n"), String::from("#a = 2\n")];
        let out = replace_guc_value(lines, "a", "9", false);
        assert_eq!(out, ["a = 9\n", "#a = 2\n"]);
    }

    #[test]
    fn a_long_value_pushes_the_comment_out_by_exactly_one_space() {
        // newindent > oldindent, so `oldindent = Max(oldindent, newindent + 1)`
        // gives the comment a single separating space.
        let lines = vec![String::from("#a = 1\t# c\n")];
        let out = replace_guc_value(lines, "a", "averyverylongvaluehere", false);
        assert_eq!(out, ["a = averyverylongvaluehere # c\n"]);
    }

    #[test]
    fn padding_uses_tabs_while_a_tab_fits_and_spaces_after_that() {
        // `#a = 1` puts its comment at de-tabified column 8; the replacement
        // `a = 12` is 6 bytes, and a tab from 6 lands exactly on 8.
        let lines = vec![String::from("#a = 1\t# c\n")];
        assert_eq!(
            replace_guc_value(lines, "a", "12", false),
            ["a = 12\t# c\n"]
        );
        // The comment here sits at column 9: a tab from 6 reaches 8, and the
        // last column is a space because a second tab would overshoot.
        let lines = vec![String::from("#a = 1 \t # c\n")];
        assert_eq!(
            replace_guc_value(lines, "a", "12", false),
            ["a = 12\t # c\n"]
        );
    }

    #[test]
    fn the_last_hash_on_the_line_starts_the_comment() {
        let lines = vec![String::from("#a = 1\t# c # d\n")];
        let out = replace_guc_value(lines, "a", "2", false);
        // `# c ` becomes padding out to the second '#', at column 12.
        assert_eq!(out, ["a = 2\t    # d\n"], "strrchr, not strchr");
    }

    #[test]
    fn a_match_keeps_the_files_spelling_of_the_name() {
        let lines = vec![String::from("#work_mem = 4MB\n")];
        let out = replace_guc_value(lines, "WORK_MEM", "512", false);
        assert_eq!(out, ["work_mem = 512\n"]);
    }

    #[test]
    fn a_commented_replacement_keeps_the_files_spelling_too() {
        let lines = vec![String::from("#Port = 5432\n")];
        let out = replace_guc_value(lines, "port", "5433", true);
        assert_eq!(out, ["#Port = 5433\n"]);
    }

    // --- the values setup_config formats --------------------------------

    #[test]
    fn a_whole_gigabyte_of_wal_is_written_as_gb() {
        assert_eq!(pretty_wal_size(64, 16), "1GB");
        assert_eq!(pretty_wal_size(5, 16), "80MB");
        assert_eq!(pretty_wal_size(64, 1), "64MB");
        assert_eq!(pretty_wal_size(64, 1024), "64GB");
    }

    #[test]
    fn a_whole_megabyte_of_buffers_is_written_as_mb() {
        assert_eq!(shared_buffers_value(16384), "128MB");
        assert_eq!(shared_buffers_value(1024), "8MB");
        assert_eq!(shared_buffers_value(100), "800kB");
    }

    #[test]
    fn the_flush_after_defaults_are_rendered_in_kilobytes() {
        assert_eq!(flush_after_value(64), "512kB");
        assert_eq!(flush_after_value(32), "256kB");
    }

    #[test]
    fn a_date_order_names_its_datestyle() {
        assert_eq!(DateOrder::Ymd.datestyle(), "iso, ymd");
        assert_eq!(DateOrder::Dmy.datestyle(), "iso, dmy");
        assert_eq!(DateOrder::Mdy.datestyle(), "iso, mdy");
        assert_eq!(DateOrder::default(), DateOrder::Mdy);
    }

    // --- auth methods ---------------------------------------------------

    fn options_with(auth: Option<&str>, local: Option<&str>, host: Option<&str>) -> Options {
        Options {
            auth: auth.map(str::to_owned),
            auth_local: local.map(str::to_owned),
            auth_host: host.map(str::to_owned),
            ..Options::default()
        }
    }

    #[test]
    fn an_unspecified_auth_method_is_trust_on_both_sides() {
        let methods = AuthMethods::resolve(&options_with(None, None, None));
        assert_eq!(methods, AuthMethods::default());
        assert_eq!(methods.local, "trust");
        assert_eq!(methods.host, "trust");
    }

    #[test]
    fn dash_a_sets_both_sides() {
        let methods = AuthMethods::resolve(&options_with(Some("md5"), None, None));
        assert_eq!(methods.local, "md5");
        assert_eq!(methods.host, "md5");
    }

    #[test]
    fn ident_becomes_peer_locally_and_peer_becomes_ident_over_tcp() {
        let methods = AuthMethods::resolve(&options_with(Some("ident"), None, None));
        assert_eq!(
            (methods.local.as_str(), methods.host.as_str()),
            ("peer", "ident")
        );
        let methods = AuthMethods::resolve(&options_with(Some("peer"), None, None));
        assert_eq!(
            (methods.local.as_str(), methods.host.as_str()),
            ("peer", "ident")
        );
    }

    #[test]
    fn the_per_side_switches_override_dash_a() {
        let methods = AuthMethods::resolve(&options_with(
            Some("trust"),
            Some("peer"),
            Some("scram-sha-256"),
        ));
        assert_eq!(methods.local, "peer");
        assert_eq!(methods.host, "scram-sha-256");
    }

    /// Divergence (`docs/divergences.md`): `-A` written last loses here.
    #[test]
    fn a_trailing_dash_a_does_not_win_over_a_per_side_switch() {
        // C's getopt, given `--auth-host md5 -A trust`, ends with host=trust.
        let methods = AuthMethods::resolve(&options_with(Some("trust"), None, Some("md5")));
        assert_eq!(methods.host, "md5", "the per-side switch always wins here");
    }

    #[test]
    fn trust_on_either_side_brings_the_caution_block() {
        for (local, host) in [("trust", "trust"), ("trust", "md5"), ("peer", "trust")] {
            let methods = AuthMethods {
                local: local.to_owned(),
                host: host.to_owned(),
            };
            assert_eq!(methods.auth_comment(), AUTHTRUST_WARNING);
        }
        let methods = AuthMethods {
            local: String::from("peer"),
            host: String::from("scram-sha-256"),
        };
        assert_eq!(methods.auth_comment(), "");
    }

    #[test]
    fn md5_on_one_side_drags_password_encryption_back_unless_scram_is_on_the_other() {
        let md5 = |local: &str, host: &str| {
            AuthMethods {
                local: local.to_owned(),
                host: host.to_owned(),
            }
            .forces_md5_password_encryption()
        };
        assert!(md5("md5", "md5"));
        assert!(md5("md5", "trust"));
        assert!(md5("peer", "md5"));
        assert!(!md5("md5", "scram-sha-256"));
        assert!(!md5("scram-sha-256", "md5"));
        assert!(!md5("trust", "trust"));
    }

    // --- the rendered files ---------------------------------------------

    #[test]
    fn the_rendered_conf_carries_every_value_setup_config_sets() {
        let settings = Settings {
            max_connections: 100,
            autovacuum_worker_slots: 16,
            shared_buffers_blocks: 16384,
            default_timezone: Some(String::from("Etc/UTC")),
            ..Settings::default()
        };
        let rendered = render_postgresql_conf(POSTGRESQL_CONF_SAMPLE, &settings);
        assert_eq!(
            line_for(&rendered, "max_connections"),
            Some("max_connections = 100\t\t\t# (change requires restart)")
        );
        assert_eq!(
            line_for(&rendered, "shared_buffers"),
            Some("shared_buffers = 128MB\t\t\t# min 128kB")
        );
        assert_eq!(
            line_for(&rendered, "timezone"),
            Some("timezone = 'Etc/UTC'")
        );
        assert_eq!(
            line_for(&rendered, "log_timezone"),
            Some("log_timezone = 'Etc/UTC'")
        );
        assert_eq!(
            line_for(&rendered, "datestyle"),
            Some("datestyle = 'iso, mdy'")
        );
        assert_eq!(
            line_for(&rendered, "default_text_search_config"),
            Some("default_text_search_config = 'pg_catalog.simple'")
        );
        assert_eq!(
            line_for(&rendered, "max_wal_size"),
            Some("max_wal_size = 1GB")
        );
        assert_eq!(
            line_for(&rendered, "min_wal_size"),
            Some("min_wal_size = 80MB")
        );
        assert_eq!(
            line_for(&rendered, "dynamic_shared_memory_type"),
            Some("dynamic_shared_memory_type = posix\t# the default is usually the first option")
        );
    }

    #[test]
    fn the_compile_time_fixups_stay_commented_out() {
        let rendered = render_postgresql_conf(POSTGRESQL_CONF_SAMPLE, &Settings::default());
        assert!(rendered.contains(&format!(
            "#unix_socket_directories = '{}'",
            pg_config::DEFAULT_PGSOCKET_DIR
        )));
        assert!(rendered.contains(&format!("#port = {}", pg_config::DEF_PGPORT_STR)));
        assert_eq!(line_for(&rendered, "port"), None);
        assert_eq!(line_for(&rendered, "unix_socket_directories"), None);
        for (name, blocks) in pg_config::FLUSH_AFTER_DEFAULTS {
            if blocks > 0 {
                assert!(
                    rendered.contains(&format!("#{name} = {}", flush_after_value(blocks))),
                    "{name}"
                );
                assert_eq!(line_for(&rendered, name), None, "{name}");
            }
        }
    }

    #[test]
    fn a_wal_segsize_moves_both_wal_size_defaults() {
        let settings = Settings {
            wal_segment_size_mb: 1,
            ..Settings::default()
        };
        let rendered = render_postgresql_conf(POSTGRESQL_CONF_SAMPLE, &settings);
        assert_eq!(
            line_for(&rendered, "min_wal_size"),
            Some("min_wal_size = 5MB")
        );
        assert_eq!(
            line_for(&rendered, "max_wal_size"),
            Some("max_wal_size = 64MB")
        );
    }

    #[test]
    fn group_access_relaxes_the_log_file_mode() {
        let owner = render_postgresql_conf(POSTGRESQL_CONF_SAMPLE, &Settings::default());
        assert_eq!(line_for(&owner, "log_file_mode"), None);
        let settings = Settings {
            perm: DataDirPerm::GROUP,
            ..Settings::default()
        };
        let group = render_postgresql_conf(POSTGRESQL_CONF_SAMPLE, &settings);
        assert_eq!(
            line_for(&group, "log_file_mode"),
            Some("log_file_mode = 0640\t\t\t# creation mode for log files,")
        );
    }

    #[test]
    fn md5_auth_writes_password_encryption() {
        let settings = Settings {
            auth: AuthMethods {
                local: String::from("md5"),
                host: String::from("md5"),
            },
            ..Settings::default()
        };
        let rendered = render_postgresql_conf(POSTGRESQL_CONF_SAMPLE, &settings);
        assert_eq!(
            line_for(&rendered, "password_encryption"),
            Some("password_encryption = md5\t\t# scram-sha-256 or (deprecated) md5")
        );
    }

    #[test]
    fn a_set_override_beats_the_value_setup_config_chose() {
        let settings = Settings {
            gucs: vec![(String::from("max_connections"), String::from("42"))],
            ..Settings::default()
        };
        let rendered = render_postgresql_conf(POSTGRESQL_CONF_SAMPLE, &settings);
        assert_eq!(
            line_for(&rendered, "max_connections"),
            Some("max_connections = 42\t\t\t# (change requires restart)")
        );
    }

    #[test]
    fn a_set_of_an_unknown_parameter_is_appended_at_the_end() {
        let settings = Settings {
            gucs: vec![(String::from("foo"), String::from("bar"))],
            ..Settings::default()
        };
        let rendered = render_postgresql_conf(POSTGRESQL_CONF_SAMPLE, &settings);
        assert!(rendered.ends_with("foo = bar\n"), "appended, not inserted");
    }

    #[test]
    fn the_hba_file_gets_both_auth_methods_and_no_tokens_survive() {
        let settings = Settings {
            auth: AuthMethods {
                local: String::from("peer"),
                host: String::from("scram-sha-256"),
            },
            ..Settings::default()
        };
        let rendered = render_pg_hba_conf(PG_HBA_CONF_SAMPLE, &settings);
        assert_no_tokens_survive(&rendered);
        assert!(
            rendered
                .contains("local   all             all                                     peer\n")
        );
        assert!(rendered.contains(
            "host    all             all             127.0.0.1/32            scram-sha-256\n"
        ));
        assert!(
            !rendered.contains(AUTHTRUST_WARNING),
            "neither side trusts, so no caution block"
        );
    }

    #[test]
    fn a_trusting_cluster_gets_the_caution_block_where_the_token_was() {
        let rendered = render_pg_hba_conf(PG_HBA_CONF_SAMPLE, &Settings::default());
        assert!(rendered.contains(AUTHTRUST_WARNING));
        assert_no_tokens_survive(&rendered);
    }

    #[test]
    fn without_ipv6_the_two_colon_colon_one_records_are_commented_out() {
        let settings = Settings {
            ipv6_supported: false,
            ..Settings::default()
        };
        let rendered = render_pg_hba_conf(PG_HBA_CONF_SAMPLE, &settings);
        assert!(rendered.contains("#host    all             all             ::1/128"));
        assert!(rendered.contains("#host    replication     all             ::1/128"));
        assert!(!rendered.contains("\nhost    all             all             ::1/128"));
    }

    #[test]
    fn the_ident_file_is_the_template_unchanged() {
        assert_eq!(
            render_pg_ident_conf(PG_IDENT_CONF_SAMPLE),
            PG_IDENT_CONF_SAMPLE
        );
    }

    #[test]
    fn the_auto_conf_is_the_two_lines_alter_system_expects() {
        assert_eq!(
            render_postgresql_auto_conf(),
            "# Do not edit this file manually!\n\
             # It will be overwritten by the ALTER SYSTEM command.\n"
        );
    }

    #[test]
    fn render_all_names_the_four_files_in_upstream_order() {
        let files = render_all(&Settings::default());
        assert_eq!(
            files.iter().map(|(name, _)| *name).collect::<Vec<_>>(),
            CONF_FILES
        );
        assert!(files.iter().all(|(_, body)| body.ends_with('\n')));
    }
}
